### ISSUE TITLE
Example Links in Readme broken

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse-uprotocol/uprotocol-sdk-java#3]
The example links in README.adoc are broken

https://github.com/eclipse-uprotocol/uprotocol-sdk-java/blob/main/sdk/src/test/java/org/eclipse/uprotocol/uri/factory/UriFactoryTest.java -> 404
Should probably be https://github.com/eclipse-uprotocol/uprotocol-sdk-java/blob/main/src/test/java/org/eclipse/uprotocol/uri/factory/UriFactoryTest.java

https://github.com/eclipse-uprotocol/uprotocol-sdk-java/blob/main/sdk/src/test/java/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactoryTest.java -> 404
Should probably be https://github.com/eclipse-uprotocol/uprotocol-sdk-java/blob/main/src/test/java/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactoryTest.java

**Comment by gkreyssing** [comment]
Following links are also broken:
- https://github.com/eclipse-uprotocol/uprotocol-sdk-java/blob/main/examples/README.adoc 
- https://github.com/eclipse-uprotocol/uprotocol

**Comment by stevenhartley** [comment]
Thanks, fixed them!
